### ISSUE TITLE
contract deploy does not wait for miner

### ISSUE THREAD

**Issue by smart-t** [gakonst/ViperWeb3Deploy#1]
This probably works fine on the testrpc but with Rinkeby.io it will need to wait for the miner.

**Comment by gakonst** [comment]
Agreed. I just quickly hacked this together.
Making it wait for the transaction to be mined would done as described here:
https://ethereum.stackexchange.com/questions/9636/whats-the-proper-way-to-wait-for-a-transaction-to-be-mined-and-get-the-results

**Comment by smart-t** [comment]
I fixed this issue and also added two parameters (one for GAS and one for PARAMETERS). Included my extended greeter example. I hope you appreciate. If you accept my pull request I think you could close this issue as wel. Have a nice day!

**Comment by gakonst** [comment]
Made some changes over your changes, including a call to setGreeting to show before/after comparison. 

Thanks for contributing!
